"""Template wizard API endpoints — multi-step guided setup."""
import logging

from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from typing import Optional

from app.middleware import get_current_user
from app.services.template_engine import (
    TEMPLATES, get_template_steps, build_step_payload, build_array_payloads,
)
from app.services.wizard_engine import WIZARD_REGISTRY
from app.services.proxysql import proxysql_service
from app.services.sync_service import sync_service, SyncAction
from app.utils.db_helpers import get_proxysql_credentials

router = APIRouter()
logger = logging.getLogger(__name__)


# ── Request models ──────────────────────────────────────


class TemplateExecuteRequest(BaseModel):
    template_id: str
    server_id: str
    architecture_mode: str
    shared_values: dict = {}
    step_values: dict  # {step_key: {field_name: value}}
    skipped_steps: list[str] = []
    options: dict = {"auto_apply": True, "auto_save": False}


class TemplatePreviewRequest(BaseModel):
    template_id: str
    server_id: str
    architecture_mode: str
    shared_values: dict = {}
    step_values: dict  # {step_key: {field_name: value}}
    skipped_steps: list[str] = []


# ── Endpoints ──────────────────────────────────────────


@router.get("/templates")
async def get_templates(user=Depends(get_current_user)):
    """List all available template definitions."""
    result = []
    for tid, template in TEMPLATES.items():
        result.append({
            "id": template.id,
            "name": template.name,
            "description": template.description,
            "icon": template.icon,
            "architecture_options": template.architecture_options,
        })
    return {"templates": result}


@router.get("/templates/{template_id}")
async def get_template_detail(template_id: str, user=Depends(get_current_user)):
    """Get a template definition with its shared fields and architecture options."""
    template = TEMPLATES.get(template_id)
    if not template:
        raise HTTPException(status_code=404, detail=f"Template '{template_id}' not found")

    shared_fields = []
    for sf in template.shared_fields:
        shared_fields.append({
            "name": sf.name,
            "label": sf.label,
            "type": sf.type,
            "required": sf.required,
            "default": sf.default,
            "help": sf.help_text,
            "placeholder": sf.placeholder,
            "min": sf.min,
            "max": sf.max,
        })

    return {
        "id": template.id,
        "name": template.name,
        "description": template.description,
        "icon": template.icon,
        "architecture_options": template.architecture_options,
        "shared_fields": shared_fields,
        "shared_field_mappings": template.shared_field_mappings,
    }


@router.get("/templates/{template_id}/steps")
async def get_template_steps_endpoint(
    template_id: str,
    architecture_mode: str,
    user=Depends(get_current_user),
):
    """Get the ordered list of steps for a template + architecture mode.

    This is called after the user selects an architecture mode, to build
    the stepper UI.
    """
    template = TEMPLATES.get(template_id)
    if not template:
        raise HTTPException(status_code=404, detail=f"Template '{template_id}' not found")

    # Validate architecture mode
    valid_modes = [opt["value"] for opt in template.architecture_options]
    if architecture_mode not in valid_modes:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid architecture mode '{architecture_mode}'. Valid: {valid_modes}"
        )

    steps = get_template_steps(template_id, architecture_mode)
    return {"steps": steps}


@router.post("/templates/preview")
async def preview_template(data: TemplatePreviewRequest, user=Depends(get_current_user)):
    """Preview all SQL statements that would be generated by the template."""
    template = TEMPLATES.get(data.template_id)
    if not template:
        raise HTTPException(status_code=404, detail=f"Template '{data.template_id}' not found")

    steps = get_template_steps(data.template_id, data.architecture_mode)
    all_sql = []
    step_results = []

    for step_info in steps:
        step_key = step_info["step_key"]
        if step_key in data.skipped_steps and step_info["skip_allowed"]:
            step_results.append({
                "step_key": step_key,
                "wizard_id": step_info["wizard_id"],
                "title": step_info["title"],
                "skipped": True,
                "sql_preview": [],
            })
            continue

        wizard_id = step_info["wizard_id"]
        wizard = WIZARD_REGISTRY.get(wizard_id)
        if not wizard:
            step_results.append({
                "step_key": step_key,
                "wizard_id": wizard_id,
                "title": step_info["title"],
                "skipped": False,
                "error": f"Wizard '{wizard_id}' not found",
                "sql_preview": [],
            })
            continue

        step_vals = data.step_values.get(step_key, {})
        has_array = bool(step_info.get("array_fields"))

        if has_array:
            payloads = build_array_payloads(step_info, step_vals, data.shared_values)
        else:
            payloads = [build_step_payload(step_info, step_vals, data.shared_values)]

        for payload in payloads:
            preview = wizard.preview_sql(payload)
            if preview.get("ok"):
                sqls = preview.get("sql_preview", [])
                all_sql.extend(sqls)
                step_results.append({
                    "step_key": step_key,
                    "wizard_id": wizard_id,
                    "title": step_info["title"],
                    "skipped": False,
                    "sql_preview": sqls,
                })
            else:
                step_results.append({
                    "step_key": step_key,
                    "wizard_id": wizard_id,
                    "title": step_info["title"],
                    "skipped": False,
                    "errors": preview.get("errors", []),
                    "sql_preview": [],
                })

    return {
        "ok": True,
        "total_sql_count": len(all_sql),
        "sql_preview": all_sql,
        "step_results": step_results,
    }


@router.post("/templates/execute")
async def execute_template(
    data: TemplateExecuteRequest,
    user=Depends(get_current_user),
):
    """Execute all steps of a template in sequence.

    For steps with array fields (e.g. multiple backend servers), each
    row generates a separate wizard execution.
    """
    template = TEMPLATES.get(data.template_id)
    if not template:
        raise HTTPException(status_code=404, detail=f"Template '{data.template_id}' not found")

    host, port, admin_user, password = await get_proxysql_credentials(data.server_id)
    steps = get_template_steps(data.template_id, data.architecture_mode)
    options = data.options or {}
    auto_apply = options.get("auto_apply", True)
    auto_save = options.get("auto_save", False)

    all_results = []
    all_sql = []
    all_ok = True
    affected_modules = set()

    for step_info in steps:
        step_key = step_info["step_key"]
        if step_key in data.skipped_steps and step_info["skip_allowed"]:
            all_results.append({
                "step_key": step_key,
                "wizard_id": step_info["wizard_id"],
                "title": step_info["title"],
                "skipped": True,
                "ok": True,
                "results": [],
            })
            continue

        wizard_id = step_info["wizard_id"]
        wizard = WIZARD_REGISTRY.get(wizard_id)
        if not wizard:
            all_ok = False
            all_results.append({
                "step_key": step_key,
                "wizard_id": wizard_id,
                "title": step_info["title"],
                "skipped": False,
                "ok": False,
                "error": f"Wizard '{wizard_id}' not found",
            })
            continue

        step_vals = data.step_values.get(step_key, {})
        has_array = bool(step_info.get("array_fields"))

        if has_array:
            payloads = build_array_payloads(step_info, step_vals, data.shared_values)
        else:
            payloads = [build_step_payload(step_info, step_vals, data.shared_values)]

        for payload in payloads:
            result = await wizard.execute(
                host, port, admin_user, password, payload,
                auto_apply=False,  # Apply all at once at the end
                auto_save=False,
            )
            all_sql.extend(result.get("executed_sql", []))
            if not result.get("ok"):
                all_ok = False
            if wizard.definition.auto_apply_module:
                affected_modules.add(wizard.definition.auto_apply_module)
            all_results.append({
                "step_key": step_key,
                "wizard_id": wizard_id,
                "title": step_info["title"],
                "skipped": False,
                **result,
            })

    # Apply all changes at once if auto_apply is set
    if auto_apply and all_ok and affected_modules:
        for module in affected_modules:
            try:
                await sync_service.sync_action(
                    host, port, admin_user, password,
                    SyncAction.APPLY,
                    tables=[],  # Empty means apply all for this module
                )
            except Exception as e:
                all_results.append({
                    "step_key": "auto_apply",
                    "wizard_id": "",
                    "title": f"LOAD {module} TO RUNTIME",
                    "ok": False,
                    "error": str(e),
                })
                all_ok = False

    # Save all changes to disk if auto_save is set
    if auto_save and all_ok and affected_modules:
        try:
            await sync_service.sync_action(
                host, port, admin_user, password,
                SyncAction.SAVE,
                tables=[],
            )
        except Exception as e:
            all_results.append({
                "step_key": "auto_save",
                "wizard_id": "",
                "title": "SAVE ALL TO DISK",
                "ok": False,
                "error": str(e),
            })
            all_ok = False

    # Store in wizard history (non-critical — do not fail the request if it errors)
    from app.database import get_db
    import json
    try:
        db = await get_db()
        try:
            user_cursor = await db.execute("SELECT id FROM users WHERE id = ?", (user["id"],))
            if not await user_cursor.fetchone():
                logger.warning("template_history: user_id=%s not found in users table", user["id"])
            else:
                server_cursor = await db.execute(
                    "SELECT id FROM server_configs WHERE id = ?", (data.server_id,)
                )
                if not await server_cursor.fetchone():
                    logger.warning(
                        "template_history: server_id=%s not found in server_configs table",
                        data.server_id,
                    )
                else:
                    await db.execute(
                        """INSERT INTO wizard_history
                           (user_id, server_id, wizard_id, wizard_name, category,
                            submitted_fields, executed_sql, auto_apply, auto_save, success, error_message)
                           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                        (user["id"], data.server_id, data.template_id,
                         template.name, "template",
                         json.dumps({"shared": data.shared_values, "steps": data.step_values,
                                     "skipped": data.skipped_steps, "mode": data.architecture_mode}),
                         json.dumps(all_sql),
                         1 if auto_apply else 0,
                         1 if auto_save else 0,
                         1 if all_ok else 0,
                         None if all_ok else "Some steps failed")
                    )
                    await db.commit()
        finally:
            await db.close()
    except Exception as exc:
        logger.warning("Failed to persist template_history: %s", exc)

    return {
        "ok": all_ok,
        "template_id": data.template_id,
        "architecture_mode": data.architecture_mode,
        "total_sql_count": len(all_sql),
        "executed_sql": all_sql,
        "step_results": all_results,
    }
