#!/usr/bin/env python3
"""Code generator: Parse ProxySQL C header and emit FastAPI models/routes.

Usage:
    python -m codegen.gen_fastapi_models --header <path_to_header.h> --outdir <output_dir>

This is the main entry point for the code generation pipeline:
  1. Read the C header file
  2. Extract and resolve #define macros
  3. Filter for current (non-versioned) table definitions
  4. Parse CREATE TABLE/VIEW SQL
  5. Emit Pydantic models, CRUD routes, and table metadata
"""
import argparse
import os
import sys
from pathlib import Path

from codegen.parser import (
    read_header, extract_defines, resolve_defines,
    is_current_table, parse_create_table,
)
from codegen.emitter import emit_models, emit_crud_router, emit_metadata


def main():
    parser = argparse.ArgumentParser(
        description="Generate FastAPI models and routes from ProxySQL C header"
    )
    parser.add_argument(
        "--header",
        required=True,
        help="Path to ProxySQL_Admin_Tables_Definitions.h"
    )
    parser.add_argument(
        "--outdir",
        required=True,
        help="Output directory for generated files"
    )
    parser.add_argument(
        "--skip",
        nargs="*",
        default=[],
        help="Files to skip (models, routes, metadata)"
    )
    args = parser.parse_args()

    # Phase 1: Read header
    print(f"[1/5] Reading header: {args.header}")
    text = read_header(args.header)

    # Phase 2: Extract defines
    print("[2/5] Extracting #define macros...")
    defines = extract_defines(text)
    print(f"      Found {len(defines)} macros")

    # Phase 3: Resolve alias chains and filter
    print("[3/5] Resolving aliases and filtering current tables...")
    resolved = resolve_defines(defines)
    current_tables = {
        name: sql for name, sql in resolved.items()
        if is_current_table(name)
    }
    print(f"      {len(current_tables)} current table definitions")

    # Phase 4: Parse CREATE TABLE SQL
    print("[4/5] Parsing CREATE TABLE statements...")
    tables = []
    errors = []
    for macro_name, sql in sorted(current_tables.items(), key=lambda x: len(x[0])):
        try:
            table_def = parse_create_table(sql, macro_name)
            # Deduplicate: keep the one with the shortest macro name
            existing = [t for t in tables if t.table_name == table_def.table_name]
            if existing and len(macro_name) >= len(existing[0].macro_name):
                continue
            if existing:
                tables.remove(existing[0])
            tables.append(table_def)
        except Exception as e:
            errors.append(f"Error parsing {macro_name}: {e}")

    if errors:
        print(f"      WARNING: {len(errors)} parse errors:")
        for err in errors[:5]:
            print(f"        {err}")

    print(f"      {len(tables)} unique tables parsed")

    # Phase 5: Emit code
    print(f"[5/5] Generating code to: {args.outdir}")
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    # __init__.py
    with open(outdir / "__init__.py", "w") as f:
        f.write("# Auto-generated by gen_fastapi_models.py\n")

    # models.py
    if "models" not in args.skip:
        models_path = outdir / "models.py"
        with open(models_path, "w") as f:
            emit_models(tables, f)
        print(f"      Generated: {models_path}")

    # routes.py
    if "routes" not in args.skip:
        routes_path = outdir / "routes.py"
        with open(routes_path, "w") as f:
            emit_crud_router(tables, f)
        print(f"      Generated: {routes_path}")

    # metadata.py
    if "metadata" not in args.skip:
        metadata_path = outdir / "metadata.py"
        with open(metadata_path, "w") as f:
            emit_metadata(tables, f)
        print(f"      Generated: {metadata_path}")

    print("\nDone! Code generation complete.")

    # Summary
    writable = [t for t in tables if not t.is_readonly]
    readonly = [t for t in tables if t.is_readonly]
    print(f"\nSummary:")
    print(f"  Total tables: {len(tables)}")
    print(f"  Writable config tables: {len(writable)}")
    print(f"  Readonly tables (stats/runtime/views): {len(readonly)}")


if __name__ == "__main__":
    main()
