#!/usr/bin/env python3
"""
One-click test environment setup script.
Creates .env.test, initializes app_test.db, verifies Docker environment.
"""
import os
import sys
import subprocess
import json

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)
ENV_FILE = os.path.join(ROOT_DIR, ".env.test")
DATA_DIR = os.path.join(ROOT_DIR, "backend", "data")
DB_FILE = os.path.join(DATA_DIR, "app_test.db")


def write_env_test():
    """Write .env.test with all required test configuration."""
    content = """# ProxySQL Admin WebUI — Test Environment Configuration
# Auto-generated by scripts/setup_test_env.py
# DO NOT use in production!

# Security (test-only keys)
SECRET_KEY=test-secret-key-min-32-chars!!
FERNET_KEY=02F01gw2gjGLev9LC_hGdPYx4cyU4qEAyWWAA4Pa85g=

# Database (SQLite, separate from production)
DATABASE_URL=sqlite:///data/app_test.db

# Auth
ACCESS_TOKEN_EXPIRE_MINUTES=60
REFRESH_TOKEN_EXPIRE_DAYS=7

# CORS
CORS_ORIGINS=http://localhost:8080,http://localhost:5173

# Logging
LOG_LEVEL=INFO

# ProxySQL defaults (connects to Docker test ProxySQL)
PROXYSQL_DEFAULT_HOST=127.0.0.1
PROXYSQL_DEFAULT_PORT=6032
# ⚠️ MUST use proxysql_remote (admin user cannot connect remotely)
PROXYSQL_DEFAULT_USER=proxysql_remote
PROXYSQL_DEFAULT_PASSWORD=remote123

# Initial admin credentials
PROXYWEB_ADMIN_USER=admin
PROXYWEB_ADMIN_PASSWORD=admin123

# ── Rate Limiting (DISABLED for testing) ──
RATE_LIMIT_ENABLED=false

# ── Cache (DISABLED for testing) ──
CACHE_ENABLED=false
"""
    with open(ENV_FILE, "w") as f:
        f.write(content)
    print(f"✅ Created {ENV_FILE}")


def init_test_db():
    """Initialize app_test.db with admin user."""
    os.makedirs(DATA_DIR, exist_ok=True)

    try:
        import sqlite3
        import bcrypt

        h = bcrypt.hashpw(b"admin123", bcrypt.gensalt()).decode()
        conn = sqlite3.connect(DB_FILE)
        c = conn.cursor()

        # Create users table
        c.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                is_admin INTEGER DEFAULT 1,
                is_active INTEGER DEFAULT 1,
                created_at TEXT DEFAULT (datetime('now')),
                updated_at TEXT DEFAULT (datetime('now'))
            )
        """)

        # Upsert admin user
        c.execute("SELECT id FROM users WHERE username='admin'")
        if c.fetchone():
            c.execute("UPDATE users SET password_hash=? WHERE username='admin'", (h,))
            print("✅ Updated admin password in app_test.db")
        else:
            c.execute("INSERT INTO users (username, password_hash) VALUES (?, ?)",
                      ("admin", h))
            print("✅ Created admin user in app_test.db")

        conn.commit()
        conn.close()
        print(f"✅ Database initialized: {DB_FILE}")
    except ImportError:
        print("⚠️ bcrypt not installed — run: pip install bcrypt")
        print("   Then manually initialize the database.")
        sys.exit(1)


def check_docker():
    """Verify Docker containers are running."""
    print("\n── Checking Docker ──")
    try:
        result = subprocess.run(
            ["docker", "ps", "--format", "{{.Names}}"],
            capture_output=True, text=True, timeout=10
        )
        containers = result.stdout.strip().split("\n")

        required = ["proxysql-test-mysql", "proxysql-test-proxysql"]
        all_ok = True
        for c in required:
            if c in containers:
                print(f"  ✅ {c} is running")
            else:
                print(f"  ❌ {c} is NOT running")
                all_ok = False

        if not all_ok:
            print("\n  Run: docker compose -f docker-compose.test.yml up -d")
            return False
        return True
    except FileNotFoundError:
        print("  ❌ Docker not found")
        return False
    except subprocess.TimeoutExpired:
        print("  ❌ Docker daemon not responding")
        return False


def verify_proxysql_users():
    """Verify ProxySQL has the remote user configured."""
    print("\n── Checking ProxySQL Users ──")
    try:
        # Check remote user
        result = subprocess.run(
            ["mysql", "-h", "127.0.0.1", "-P", "6032", "-u", "proxysql_remote",
             "-premote123", "-e", "SELECT 1 AS ok"],
            capture_output=True, text=True, timeout=10
        )
        if "ok" in result.stdout:
            print("  ✅ proxysql_remote:remote123 works")
            return True
        else:
            print("  ❌ proxysql_remote not working")
            print("  Output:", result.stdout, result.stderr)
            return False
    except FileNotFoundError:
        print("  ⚠️ mysql CLI not installed — skipping ProxySQL verification")
        return True  # Don't fail if CLI not available
    except subprocess.TimeoutExpired:
        print("  ❌ ProxySQL connection timed out")
        return False


def main():
    print("=" * 60)
    print("ProxySQL Admin WebUI — Test Environment Setup")
    print("=" * 60)

    # Step 1: Write .env.test
    print("\n── Step 1: Configuration ──")
    write_env_test()

    # Step 2: Initialize database
    print("\n── Step 2: Database ──")
    init_test_db()

    # Step 3: Docker check
    print("\n── Step 3: Docker ──")
    docker_ok = check_docker()

    # Step 4: ProxySQL user verification
    if docker_ok:
        verify_proxysql_users()

    # Summary
    print(f"\n{'=' * 60}")
    print("Setup complete! Next steps:")
    print()
    print("  # Start Docker (if not running):")
    print("  docker compose -f docker-compose.test.yml up -d")
    print()
    print("  # Start backend:")
    print("  cd backend && ENV_FILE=/workspace/.env.test python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload")
    print()
    print("  # Start frontend (optional, for L3):")
    print("  cd frontend && npx vite --host")
    print()
    print("  # Run tests:")
    print("  bash scripts/test_all.sh --quick    # L0-L3 only")
    print("  bash scripts/test_all.sh --api      # L4-L5 only")
    print("  bash scripts/test_all.sh            # All L0-L5")
    print("=" * 60)


if __name__ == "__main__":
    main()
